### ISSUE TITLE
Namespace Overlap Preventing Recording Multiple Devices(with the same default sampling rate) Simultaneously

### ISSUE THREAD

**Issue by AbelHo** [OpenAcousticDevices/AudioMoth-USB-Microphone#1]
For example when multiple "384kHz AudioMoth USB Microphone" devices are connected, it will show up as only one device. So only one device can record at one time.
If the default sampling rate is different, the namespace won't overlap and it can all be accessed individually.

Could this be fixed by adding 1,2,3 etc to the device name instead of just using the same name for each default sampling rate so it doesn't clash?
If not, an easy less elegant quick fix would be to add some random string to it so it has low probability of name clashing.

It will take me some effort to install the toolchain to test the changes, it would be great if someone could help with this. Thanks in advance :)

**Comment by AbelHo** [comment]
It has been resolved with 69d0e51 version 1.2.2?

**Comment by AlexRogersCS** [comment]
Yes. Version 1.2.2 adds the device serial ID to the USB serial number string so the OS will detect and show multiple devices, even if they have the same sample rate configured.
